// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meridian.proto

// Meridian's single stable contract, expressed as a language-neutral IDL.
//
// This file is the source of truth that every language binding implements:
// the TypeScript engine serves it (src/proxy/grpc-server.ts) and the Python
// engine both serves and consumes it (clients/python/meridian). Keeping the
// contract here — rather than only in TypeScript types — is what makes
// Meridian polyglot.
//
// Arbitrary JSON payloads (request body, normalized response data, error
// metadata) are carried as JSON-encoded strings rather than
// google.protobuf.Struct. This keeps the wire format trivial and the
// conversions explicit and byte-identical across languages, at the cost of a
// JSON encode/decode on each side.

package meridianv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Meridian_Call_FullMethodName       = "/meridian.v1.Meridian/Call"
	Meridian_Paginate_FullMethodName   = "/meridian.v1.Meridian/Paginate"
	Meridian_StreamCall_FullMethodName = "/meridian.v1.Meridian/StreamCall"
	Meridian_Health_FullMethodName     = "/meridian.v1.Meridian/Health"
)

// MeridianClient is the client API for Meridian service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeridianClient interface {
	// Execute a single normalized request (.get/.post/.put/.patch/.delete).
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// Traverse a paginated endpoint, streaming one CallResponse per page.
	Paginate(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallResponse], error)
	// Stream a Server-Sent-Events / token response (anthropic, openai, gemini,
	// cohere, mistral, …). Emits one StreamChunk per upstream SSE delta, then a
	// final chunk with done=true. The request defaults to POST unless `method`
	// is set explicitly.
	StreamCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// Liveness + capability probe. Unauthenticated: returns no secrets.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type meridianClient struct {
	cc grpc.ClientConnInterface
}

func NewMeridianClient(cc grpc.ClientConnInterface) MeridianClient {
	return &meridianClient{cc}
}

func (c *meridianClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, Meridian_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meridianClient) Paginate(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Meridian_ServiceDesc.Streams[0], Meridian_Paginate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallRequest, CallResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Meridian_PaginateClient = grpc.ServerStreamingClient[CallResponse]

func (c *meridianClient) StreamCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Meridian_ServiceDesc.Streams[1], Meridian_StreamCall_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Meridian_StreamCallClient = grpc.ServerStreamingClient[StreamChunk]

func (c *meridianClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Meridian_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeridianServer is the server API for Meridian service.
// All implementations must embed UnimplementedMeridianServer
// for forward compatibility.
type MeridianServer interface {
	// Execute a single normalized request (.get/.post/.put/.patch/.delete).
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// Traverse a paginated endpoint, streaming one CallResponse per page.
	Paginate(*CallRequest, grpc.ServerStreamingServer[CallResponse]) error
	// Stream a Server-Sent-Events / token response (anthropic, openai, gemini,
	// cohere, mistral, …). Emits one StreamChunk per upstream SSE delta, then a
	// final chunk with done=true. The request defaults to POST unless `method`
	// is set explicitly.
	StreamCall(*CallRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// Liveness + capability probe. Unauthenticated: returns no secrets.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMeridianServer()
}

// UnimplementedMeridianServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeridianServer struct{}

func (UnimplementedMeridianServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedMeridianServer) Paginate(*CallRequest, grpc.ServerStreamingServer[CallResponse]) error {
	return status.Error(codes.Unimplemented, "method Paginate not implemented")
}
func (UnimplementedMeridianServer) StreamCall(*CallRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamCall not implemented")
}
func (UnimplementedMeridianServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMeridianServer) mustEmbedUnimplementedMeridianServer() {}
func (UnimplementedMeridianServer) testEmbeddedByValue()                  {}

// UnsafeMeridianServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeridianServer will
// result in compilation errors.
type UnsafeMeridianServer interface {
	mustEmbedUnimplementedMeridianServer()
}

func RegisterMeridianServer(s grpc.ServiceRegistrar, srv MeridianServer) {
	// If the following call panics, it indicates UnimplementedMeridianServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Meridian_ServiceDesc, srv)
}

func _Meridian_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeridianServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meridian_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeridianServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meridian_Paginate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeridianServer).Paginate(m, &grpc.GenericServerStream[CallRequest, CallResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Meridian_PaginateServer = grpc.ServerStreamingServer[CallResponse]

func _Meridian_StreamCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeridianServer).StreamCall(m, &grpc.GenericServerStream[CallRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Meridian_StreamCallServer = grpc.ServerStreamingServer[StreamChunk]

func _Meridian_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeridianServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meridian_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeridianServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Meridian_ServiceDesc is the grpc.ServiceDesc for Meridian service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meridian_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.v1.Meridian",
	HandlerType: (*MeridianServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Meridian_Call_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Meridian_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Paginate",
			Handler:       _Meridian_Paginate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCall",
			Handler:       _Meridian_StreamCall_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "meridian.proto",
}
