// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meridian.proto

// Meridian's single stable contract, expressed as a language-neutral IDL.
//
// This file is the source of truth that every language binding implements:
// the TypeScript engine serves it (src/proxy/grpc-server.ts) and the Python
// engine both serves and consumes it (clients/python/meridian). Keeping the
// contract here — rather than only in TypeScript types — is what makes
// Meridian polyglot.
//
// Arbitrary JSON payloads (request body, normalized response data, error
// metadata) are carried as JSON-encoded strings rather than
// google.protobuf.Struct. This keeps the wire format trivial and the
// conversions explicit and byte-identical across languages, at the cost of a
// JSON encode/decode on each side.

package meridianv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirrors MeridianErrorCategory in src/core/types.ts.
type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	ErrorCategory_AUTH                       ErrorCategory = 1
	ErrorCategory_RATE_LIMIT                 ErrorCategory = 2
	ErrorCategory_NETWORK                    ErrorCategory = 3
	ErrorCategory_PROVIDER                   ErrorCategory = 4
	ErrorCategory_VALIDATION                 ErrorCategory = 5
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "AUTH",
		2: "RATE_LIMIT",
		3: "NETWORK",
		4: "PROVIDER",
		5: "VALIDATION",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED": 0,
		"AUTH":                       1,
		"RATE_LIMIT":                 2,
		"NETWORK":                    3,
		"PROVIDER":                   4,
		"VALIDATION":                 5,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_meridian_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{0}
}

// Mirrors MeridianErrorCode in src/core/types.ts.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_AUTH_FAILED            ErrorCode = 1
	ErrorCode_RATE_LIMITED           ErrorCode = 2
	ErrorCode_NOT_FOUND              ErrorCode = 3
	ErrorCode_BAD_REQUEST            ErrorCode = 4
	ErrorCode_UPSTREAM_5XX           ErrorCode = 5
	ErrorCode_NETWORK_ERROR          ErrorCode = 6
	ErrorCode_TIMEOUT                ErrorCode = 7
	ErrorCode_UNKNOWN                ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "AUTH_FAILED",
		2: "RATE_LIMITED",
		3: "NOT_FOUND",
		4: "BAD_REQUEST",
		5: "UPSTREAM_5XX",
		6: "NETWORK_ERROR",
		7: "TIMEOUT",
		8: "UNKNOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"AUTH_FAILED":            1,
		"RATE_LIMITED":           2,
		"NOT_FOUND":              3,
		"BAD_REQUEST":            4,
		"UPSTREAM_5XX":           5,
		"NETWORK_ERROR":          6,
		"TIMEOUT":                7,
		"UNKNOWN":                8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_meridian_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{1}
}

// Mirrors CircuitState in src/core/types.ts.
type CircuitState int32

const (
	CircuitState_CIRCUIT_STATE_UNSPECIFIED CircuitState = 0
	CircuitState_CLOSED                    CircuitState = 1
	CircuitState_OPEN                      CircuitState = 2
	CircuitState_HALF_OPEN                 CircuitState = 3
)

// Enum value maps for CircuitState.
var (
	CircuitState_name = map[int32]string{
		0: "CIRCUIT_STATE_UNSPECIFIED",
		1: "CLOSED",
		2: "OPEN",
		3: "HALF_OPEN",
	}
	CircuitState_value = map[string]int32{
		"CIRCUIT_STATE_UNSPECIFIED": 0,
		"CLOSED":                    1,
		"OPEN":                      2,
		"HALF_OPEN":                 3,
	}
)

func (x CircuitState) Enum() *CircuitState {
	p := new(CircuitState)
	*p = x
	return p
}

func (x CircuitState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CircuitState) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_proto_enumTypes[2].Descriptor()
}

func (CircuitState) Type() protoreflect.EnumType {
	return &file_meridian_proto_enumTypes[2]
}

func (x CircuitState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CircuitState.Descriptor instead.
func (CircuitState) EnumDescriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{2}
}

type CallRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // e.g. "github"
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`     // GET|POST|PUT|PATCH|DELETE
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // relative path, e.g. /repos/octocat/Hello-World
	Query          map[string]string      `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers        map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodyJson       string                 `protobuf:"bytes,6,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"` // JSON-encoded request body ("" = none)
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TimeoutMs      int32                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 0 = adapter default
	Identity       string                 `protobuf:"bytes,9,opt,name=identity,proto3" json:"identity,omitempty"`                     // SOC 2 audit identity
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_meridian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CallRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CallRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *CallRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CallRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CallRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RateLimitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetUnixMs   int64                  `protobuf:"varint,3,opt,name=reset_unix_ms,json=resetUnixMs,proto3" json:"reset_unix_ms,omitempty"` // RateLimitInfo.reset as epoch millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitInfo) Reset() {
	*x = RateLimitInfo{}
	mi := &file_meridian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitInfo) ProtoMessage() {}

func (x *RateLimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitInfo.ProtoReflect.Descriptor instead.
func (*RateLimitInfo) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitInfo) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimitInfo) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitInfo) GetResetUnixMs() int64 {
	if x != nil {
		return x.ResetUnixMs
	}
	return 0
}

type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasNext       bool                   `protobuf:"varint,1,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasTotal      bool                   `protobuf:"varint,4,opt,name=has_total,json=hasTotal,proto3" json:"has_total,omitempty"` // distinguishes total=0 from "absent"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_meridian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationInfo) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *PaginationInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationInfo) GetHasTotal() bool {
	if x != nil {
		return x.HasTotal
	}
	return false
}

type RequestTrace struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Retries            int32                  `protobuf:"varint,1,opt,name=retries,proto3" json:"retries,omitempty"`
	LatencyMs          float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CircuitBreaker     CircuitState           `protobuf:"varint,3,opt,name=circuit_breaker,json=circuitBreaker,proto3,enum=meridian.v1.CircuitState" json:"circuit_breaker,omitempty"`
	RateLimitRemaining int64                  `protobuf:"varint,4,opt,name=rate_limit_remaining,json=rateLimitRemaining,proto3" json:"rate_limit_remaining,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestTrace) Reset() {
	*x = RequestTrace{}
	mi := &file_meridian_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTrace) ProtoMessage() {}

func (x *RequestTrace) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTrace.ProtoReflect.Descriptor instead.
func (*RequestTrace) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{3}
}

func (x *RequestTrace) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *RequestTrace) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RequestTrace) GetCircuitBreaker() CircuitState {
	if x != nil {
		return x.CircuitBreaker
	}
	return CircuitState_CIRCUIT_STATE_UNSPECIFIED
}

func (x *RequestTrace) GetRateLimitRemaining() int64 {
	if x != nil {
		return x.RateLimitRemaining
	}
	return 0
}

type ResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RateLimit     *RateLimitInfo         `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"` // unset when there is no next page
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Trace         *RequestTrace          `protobuf:"bytes,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_meridian_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseMeta) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ResponseMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMeta) GetRateLimit() *RateLimitInfo {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *ResponseMeta) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ResponseMeta) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ResponseMeta) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ResponseMeta) GetTrace() *RequestTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type MeridianError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Category         ErrorCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=meridian.v1.ErrorCategory" json:"category,omitempty"`
	Code             ErrorCode              `protobuf:"varint,3,opt,name=code,proto3,enum=meridian.v1.ErrorCode" json:"code,omitempty"`
	Retryable        bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Provider         string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestId        string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                                 // upstream HTTP status (0 if none)
	MetadataJson     string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`                  // JSON-encoded metadata ("" = none)
	RetryAfterUnixMs int64                  `protobuf:"varint,9,opt,name=retry_after_unix_ms,json=retryAfterUnixMs,proto3" json:"retry_after_unix_ms,omitempty"` // 0 if none
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeridianError) Reset() {
	*x = MeridianError{}
	mi := &file_meridian_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeridianError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeridianError) ProtoMessage() {}

func (x *MeridianError) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeridianError.ProtoReflect.Descriptor instead.
func (*MeridianError) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{5}
}

func (x *MeridianError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MeridianError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *MeridianError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *MeridianError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *MeridianError) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *MeridianError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MeridianError) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MeridianError) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *MeridianError) GetRetryAfterUnixMs() int64 {
	if x != nil {
		return x.RetryAfterUnixMs
	}
	return 0
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      string                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded normalized response data
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error         *MeridianError         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // populated => the call failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_meridian_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{6}
}

func (x *CallResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *CallResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CallResponse) GetError() *MeridianError {
	if x != nil {
		return x.Error
	}
	return nil
}

// One delta of a server-streamed (SSE) response. Mirrors StreamChunk<T> in
// src/core/streaming.ts. The stream is terminated by a final chunk with
// done=true (and no data); if it carries `error`, the stream failed.
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      string                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded delta ("" on the terminal chunk)
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                      // 0-based position in the stream
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`                       // SSE event name ("" = none)
	Raw           string                 `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`                           // verbatim SSE data payload ("" on terminal/error)
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`                        // true on the final, data-less terminal chunk
	Error         *MeridianError         `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                       // populated => the stream failed (last chunk)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_meridian_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{7}
}

func (x *StreamChunk) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *StreamChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamChunk) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamChunk) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *StreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamChunk) GetError() *MeridianError {
	if x != nil {
		return x.Error
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_meridian_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Providers     []string               `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Recording     bool                   `protobuf:"varint,3,opt,name=recording,proto3" json:"recording,omitempty"`
	Replaying     bool                   `protobuf:"varint,4,opt,name=replaying,proto3" json:"replaying,omitempty"`
	AuthRequired  bool                   `protobuf:"varint,5,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_meridian_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_meridian_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *HealthResponse) GetRecording() bool {
	if x != nil {
		return x.Recording
	}
	return false
}

func (x *HealthResponse) GetReplaying() bool {
	if x != nil {
		return x.Replaying
	}
	return false
}

func (x *HealthResponse) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

var File_meridian_proto protoreflect.FileDescriptor

const file_meridian_proto_rawDesc = "" +
	"\n" +
	"\x0emeridian.proto\x12\vmeridian.v1\"\xd0\x03\n" +
	"\vCallRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x129\n" +
	"\x05query\x18\x04 \x03(\v2#.meridian.v1.CallRequest.QueryEntryR\x05query\x12?\n" +
	"\aheaders\x18\x05 \x03(\v2%.meridian.v1.CallRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tbody_json\x18\x06 \x01(\tR\bbodyJson\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x05R\ttimeoutMs\x12\x1a\n" +
	"\bidentity\x18\t \x01(\tR\bidentity\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\rRateLimitInfo\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\"\n" +
	"\rreset_unix_ms\x18\x03 \x01(\x03R\vresetUnixMs\"v\n" +
	"\x0ePaginationInfo\x12\x19\n" +
	"\bhas_next\x18\x01 \x01(\bR\ahasNext\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1b\n" +
	"\thas_total\x18\x04 \x01(\bR\bhasTotal\"\xbd\x01\n" +
	"\fRequestTrace\x12\x18\n" +
	"\aretries\x18\x01 \x01(\x05R\aretries\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12B\n" +
	"\x0fcircuit_breaker\x18\x03 \x01(\x0e2\x19.meridian.v1.CircuitStateR\x0ecircuitBreaker\x120\n" +
	"\x14rate_limit_remaining\x18\x04 \x01(\x03R\x12rateLimitRemaining\"\xb5\x02\n" +
	"\fResponseMeta\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x129\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\v2\x1a.meridian.v1.RateLimitInfoR\trateLimit\x12;\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1b.meridian.v1.PaginationInfoR\n" +
	"pagination\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x12/\n" +
	"\x05trace\x18\a \x01(\v2\x19.meridian.v1.RequestTraceR\x05trace\"\xd2\x02\n" +
	"\rMeridianError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x126\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1a.meridian.v1.ErrorCategoryR\bcategory\x12*\n" +
	"\x04code\x18\x03 \x01(\x0e2\x16.meridian.v1.ErrorCodeR\x04code\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12-\n" +
	"\x13retry_after_unix_ms\x18\t \x01(\x03R\x10retryAfterUnixMs\"\x8c\x01\n" +
	"\fCallResponse\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\tR\bdataJson\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.meridian.v1.ResponseMetaR\x04meta\x120\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.meridian.v1.MeridianErrorR\x05error\"\xae\x01\n" +
	"\vStreamChunk\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\tR\bdataJson\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\tR\x03raw\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x120\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.meridian.v1.MeridianErrorR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xa7\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\tproviders\x18\x02 \x03(\tR\tproviders\x12\x1c\n" +
	"\trecording\x18\x03 \x01(\bR\trecording\x12\x1c\n" +
	"\treplaying\x18\x04 \x01(\bR\treplaying\x12#\n" +
	"\rauth_required\x18\x05 \x01(\bR\fauthRequired*t\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AUTH\x10\x01\x12\x0e\n" +
	"\n" +
	"RATE_LIMIT\x10\x02\x12\v\n" +
	"\aNETWORK\x10\x03\x12\f\n" +
	"\bPROVIDER\x10\x04\x12\x0e\n" +
	"\n" +
	"VALIDATION\x10\x05*\xa9\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vAUTH_FAILED\x10\x01\x12\x10\n" +
	"\fRATE_LIMITED\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x04\x12\x10\n" +
	"\fUPSTREAM_5XX\x10\x05\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x06\x12\v\n" +
	"\aTIMEOUT\x10\a\x12\v\n" +
	"\aUNKNOWN\x10\b*R\n" +
	"\fCircuitState\x12\x1d\n" +
	"\x19CIRCUIT_STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x01\x12\b\n" +
	"\x04OPEN\x10\x02\x12\r\n" +
	"\tHALF_OPEN\x10\x032\x91\x02\n" +
	"\bMeridian\x12;\n" +
	"\x04Call\x12\x18.meridian.v1.CallRequest\x1a\x19.meridian.v1.CallResponse\x12A\n" +
	"\bPaginate\x12\x18.meridian.v1.CallRequest\x1a\x19.meridian.v1.CallResponse0\x01\x12B\n" +
	"\n" +
	"StreamCall\x12\x18.meridian.v1.CallRequest\x1a\x18.meridian.v1.StreamChunk0\x01\x12A\n" +
	"\x06Health\x12\x1a.meridian.v1.HealthRequest\x1a\x1b.meridian.v1.HealthResponseBLZJgithub.com/Raghaverma/meridianjs/clients/go/genproto/meridianv1;meridianv1b\x06proto3"

var (
	file_meridian_proto_rawDescOnce sync.Once
	file_meridian_proto_rawDescData []byte
)

func file_meridian_proto_rawDescGZIP() []byte {
	file_meridian_proto_rawDescOnce.Do(func() {
		file_meridian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_proto_rawDesc), len(file_meridian_proto_rawDesc)))
	})
	return file_meridian_proto_rawDescData
}

var file_meridian_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_meridian_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_meridian_proto_goTypes = []any{
	(ErrorCategory)(0),     // 0: meridian.v1.ErrorCategory
	(ErrorCode)(0),         // 1: meridian.v1.ErrorCode
	(CircuitState)(0),      // 2: meridian.v1.CircuitState
	(*CallRequest)(nil),    // 3: meridian.v1.CallRequest
	(*RateLimitInfo)(nil),  // 4: meridian.v1.RateLimitInfo
	(*PaginationInfo)(nil), // 5: meridian.v1.PaginationInfo
	(*RequestTrace)(nil),   // 6: meridian.v1.RequestTrace
	(*ResponseMeta)(nil),   // 7: meridian.v1.ResponseMeta
	(*MeridianError)(nil),  // 8: meridian.v1.MeridianError
	(*CallResponse)(nil),   // 9: meridian.v1.CallResponse
	(*StreamChunk)(nil),    // 10: meridian.v1.StreamChunk
	(*HealthRequest)(nil),  // 11: meridian.v1.HealthRequest
	(*HealthResponse)(nil), // 12: meridian.v1.HealthResponse
	nil,                    // 13: meridian.v1.CallRequest.QueryEntry
	nil,                    // 14: meridian.v1.CallRequest.HeadersEntry
}
var file_meridian_proto_depIdxs = []int32{
	13, // 0: meridian.v1.CallRequest.query:type_name -> meridian.v1.CallRequest.QueryEntry
	14, // 1: meridian.v1.CallRequest.headers:type_name -> meridian.v1.CallRequest.HeadersEntry
	2,  // 2: meridian.v1.RequestTrace.circuit_breaker:type_name -> meridian.v1.CircuitState
	4,  // 3: meridian.v1.ResponseMeta.rate_limit:type_name -> meridian.v1.RateLimitInfo
	5,  // 4: meridian.v1.ResponseMeta.pagination:type_name -> meridian.v1.PaginationInfo
	6,  // 5: meridian.v1.ResponseMeta.trace:type_name -> meridian.v1.RequestTrace
	0,  // 6: meridian.v1.MeridianError.category:type_name -> meridian.v1.ErrorCategory
	1,  // 7: meridian.v1.MeridianError.code:type_name -> meridian.v1.ErrorCode
	7,  // 8: meridian.v1.CallResponse.meta:type_name -> meridian.v1.ResponseMeta
	8,  // 9: meridian.v1.CallResponse.error:type_name -> meridian.v1.MeridianError
	8,  // 10: meridian.v1.StreamChunk.error:type_name -> meridian.v1.MeridianError
	3,  // 11: meridian.v1.Meridian.Call:input_type -> meridian.v1.CallRequest
	3,  // 12: meridian.v1.Meridian.Paginate:input_type -> meridian.v1.CallRequest
	3,  // 13: meridian.v1.Meridian.StreamCall:input_type -> meridian.v1.CallRequest
	11, // 14: meridian.v1.Meridian.Health:input_type -> meridian.v1.HealthRequest
	9,  // 15: meridian.v1.Meridian.Call:output_type -> meridian.v1.CallResponse
	9,  // 16: meridian.v1.Meridian.Paginate:output_type -> meridian.v1.CallResponse
	10, // 17: meridian.v1.Meridian.StreamCall:output_type -> meridian.v1.StreamChunk
	12, // 18: meridian.v1.Meridian.Health:output_type -> meridian.v1.HealthResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_meridian_proto_init() }
func file_meridian_proto_init() {
	if File_meridian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_proto_rawDesc), len(file_meridian_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meridian_proto_goTypes,
		DependencyIndexes: file_meridian_proto_depIdxs,
		EnumInfos:         file_meridian_proto_enumTypes,
		MessageInfos:      file_meridian_proto_msgTypes,
	}.Build()
	File_meridian_proto = out.File
	file_meridian_proto_goTypes = nil
	file_meridian_proto_depIdxs = nil
}
