#!/usr/bin/env node
// Reads the version from package.json and writes src/core/version.generated.ts.
// Hooked into prebuild and pretest so SDK_VERSION never drifts from package.json.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));

writeFileSync(
  resolve(root, "src/core/version.generated.ts"),
  `// Generated by scripts/sync-version.mjs — do not edit manually.\nexport const SDK_VERSION = "${version}";\n`,
);

console.log(`SDK_VERSION → ${version}`);
